cristalhq/aconfig

README.md

fix pkg link in README

---

README.md
aconfig.go
aconfig_test.go

custom env and flag names

---

README.md

add Cobra example to README

---

README.md
aconfig.go
aconfig_test.go

add WalkFields

---

aconfig.go
aconfig_test.go
example_test.go
reflection.go
utils.go

Divide and conquer (conquer all btw)

split into files

---

aconfig_test.go
reflection.go

Add config parsing for pointers to structs

---

aconfig.go

Add file from flag to config.Files slice when config.MergeFiles is true

merge files with file from flag

---

aconfig.go
utils.go

add .yml format

---

aconfig.go
aconfig_test.go
reflection.go
utils.go

exact name

---

aconfig.go
aconfig_test.go

duplicate name

---

.github/workflows/build.yml

add release notes

---

go.mod

bump Go version to 1.16

---

aconfigdotenv/go.mod
aconfigdotenv/go.sum
aconfighcl/go.mod
aconfighcl/go.sum
aconfigtoml/go.mod
aconfigtoml/go.sum
aconfigyaml/go.mod
aconfigyaml/go.sum

bump aconfig in decoders

---

aconfig.go

Changing the description of the FileFlag parameter to a more understandable one.

Changing the description of the FileFlag parameter

---

aconfig_test.go
utils.go

Better struct assert

---

reflection.go

Fix panic with empty arrays

---

aconfigyaml/go.mod
aconfigyaml/go.sum
aconfigyaml/res.yaml
aconfigyaml/yaml_test.go

Add yaml test with empty arrays

---

aconfigdotenv/dotenv.go
aconfigdotenv/dotenv_test.go
aconfigdotenv/go.mod
aconfigdotenv/go.sum
aconfigdotenv/testdata/config.env
aconfighcl/go.mod
aconfighcl/go.sum
aconfighcl/hcl.go
aconfighcl/hcl_test.go
aconfighcl/testdata/config.hcl
aconfigtoml/go.mod
aconfigtoml/go.sum
aconfigtoml/testdata/config.toml
aconfigtoml/toml.go
aconfigtoml/toml_test.go
aconfigyaml/go.mod
aconfigyaml/testdata/config.yaml
aconfigyaml/yaml.go
aconfigyaml/yaml_test.go

Support fsys for all decoders

---

aconfig_test.go
reflection.go

Support unmarshal custom type which implements encoding.TextUnmarshaler interface

Support unmarshal custom type

---

aconfig.go

Do not leak values in errors

---

aconfig.go
aconfig_test.go
go.mod
go.sum
parser.go
reflection.go

(hopefully :) Fixes #117 #120 
do `aconfig.Config{NewParser: true}` to enable new structure parser.

New parser

---

aconfig_test.go
reflection.go
testdata/slice-deep-structs.json

Close https://github.com/cristalhq/aconfig/issues/157

Fix: correctly support nested structs
